const images = {
    verify: require("./verify.png"),
    verifyDark: require("./verifyDark.png"),
    slide1: require("./slide1.png"),
    slide1Dark: require("./slide1Dark.png"),
    // slide1_2x: require("./slide1@2x.png"),
    // slide1_3x: require("./slide1@3x.png"),
    slide2: require("./slide2.png"),
    slide2Dark: require("./slide2Dark.png"),
    // slide2_2x: require("./slide2@2x.png"),
    // slide2_3x: require("./slide2@3x.png"),
    slide3: require("./slide3.png"),
    slide3Dark: require("./slide3Dark.png"),
    scanId: require("./scanId.png"),
    scanIdDark: require("./scanIdDark.png"),
    selfieImageDark: require("./selfieImageDark.png"),
    selfieImage: require("./selfieImage.png"),
    finishSetupDark: require("./finishSetupDark.png"),
    finishSetup: require("./finishSetup.png"),
    welcomeDark: require("./welcomeDark.png"),
    welcome: require("./welcome.png"),
    addCardDark: require("./addCardDark.png"),
    addCard: require("./addCard.png"),
    bg: require("./bg1.png"),
    profile: require("./profile.png"),
    support: require("./support.png"),
    supportDark: require("./supportDark.png"),
  };
  
  export default images;
  