const icons = {
  angleLeft: require("./angle-left.png"),
  countryIN: require("./Country=IN.png"),
  eyeSlash: require("./eye-slash.png"),
  eye: require("./eye.png"),
  lock: require("./lock.png"),
  close: require("./close.png"),
  envelope: require("./envelope.png"),
  calendar: require("./calendar-empty.png"),
  angleDown: require("./angleDown.png"),
  angleUp: require("./angleUp.png"),
  camera: require("./camera.png"),
  loading: require("./loading.png"),
  scanQr: require("./scanQr.png"),
  check: require("./check.png"),
  retry: require("./retry.png"),
  flash: require("./flash.png"),
  mastercard: require("./mastercard.png"),
  trash: require("./trash.png"),
  home: require("./home.png"),
  chat: require("./chat.png"),
  chatFill: require("./chatFill.png"),
  coins: require("./coins.png"),
  creditCardMinus: require("./creditCardMinus.png"),
  getMoney: require("./getMoney.png"),
  invoice: require("./invoice.png"),
  sack: require("./sack.png"),
  scanner: require("./scanner.png"),
  sendMoney: require("./sendMoney.png"),
  tropyStar: require("./tropyStar.png"),
  unlock: require("./unlock.png"),
  user: require("./user.png"),
  bank: require("./bank.png"),
  bell: require("./bell.png"),
  wallet: require("./wallet.png"),
  chart: require("./chart.png"),
};

export default icons;
